name: NPM Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up NodeV14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm i
      - run: npm run test